pipeline {

    agent any

    stages {

        stage('Clone Repository') {
            steps {
                echo 'Cloning Repository...'
            }
        }

        stage('Build') {
            steps {
                echo 'Building Project...'
            }
        }

        stage('Test') {
            steps {
                echo 'Running Tests...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying to AWS S3...'
            }
        }
    }
}